version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Kolkata"
      cron: "5 1 * * *"  # 1:05 AM IST

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Kolkata"
      cron: "0 14 * * *"  # 2:00 PM IST
