spring:
  data:
    mongodb:
      database: audit
      uri: mongodb://localhost:27017/audit
  kafka:
    bootstrap-servers: localhost:9092
javers:
  mongo:
    enabled: true
    database-name: audit
  auditing:
    enabled: true
  ttl:
    commit-metadata-days: 30
    snapshot-days: 30
