spring:
  application:
    name: audit
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: audit-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
javers:
  ttl:
    commit-metadata-days: 30
    snapshot-days: 30

common:
  mongock:
    changeLockCollection: mongockLock
    changeLogCollection: mongockChangeLog
    enabled: true
  mongobee: true

mongock:
  change-log-package: com.sorushi.invoice.management.audit.migration
  runner-type: ApplicationRunner
  transaction-enabled: true

