name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  pull_request_target:
    types: [opened, reopened, synchronize, edited]
  schedule:
    - cron: '30 14 * * *'
    - cron: '32 16 * * *'

jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request_target'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build without tests
        run: mvn -ntp -DskipTests package

      - name: Upload JAR Artifact (only on push/schedule)
        if: github.event_name == 'push' || github.event_name == 'schedule'
        uses: actions/upload-artifact@v4
        with:
          name: audit-jar
          path: target/*.jar

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request_target'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run Unit Tests with Coverage
        run: mvn -ntp test jacoco:report

      - name: Upload JUnit Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-report
          path: target/surefire-reports/

      - name: Upload JaCoCo Code Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-code-coverage
          path: target/site/jacoco/

  codeql-analysis:
    name: CodeQL Security Analysis
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name != 'pull_request_target'
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin
          build-mode: manual

      - name: Build Project (for CodeQL)
        run: mvn -ntp -DskipTests package

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java-kotlin"

  dependency-review:
    name: Dependency Review for PRs
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
