name: PR Labeler

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  label:
    name: Auto Label PR
    runs-on: ubuntu-latest

    steps:
      - name: Run Labeler
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
